version: '3'

services:
  frontend:
    container_name: sentence-builder-api-frontend
    ports:
      - '${FRONTEND_PORT}:3000'
    restart: always
    build:
      context: ./src/ui/sentence-builder-api-ui/.
      args:
        BACKEND_URL: ${BACKEND_URL}
        SENTENCE_BUILDER_API_PRIVATE_PATH: ${SENTENCE_BUILDER_API_PRIVATE_PATH}
    depends_on:
      - backend
    networks:
      - sentence-builder

  backend:
    container_name: sentence-builder-api-backend
    ports:
      - '${BACKEND_PORT}:8080'
    build:
      context: .
    environment:
      SENTENCE_BUILDER_API_POSTGRES_URL: ${SENTENCE_BUILDER_API_POSTGRES_URL}
      SENTENCE_BUILDER_API_POSTGRES_USER: ${SENTENCE_BUILDER_API_POSTGRES_USER}
      SENTENCE_BUILDER_API_POSTGRES_PASS: ${SENTENCE_BUILDER_API_POSTGRES_PASS}
      SENTENCE_BUILDER_API_MONGODB_URL: ${SENTENCE_BUILDER_API_MONGODB_URL}
      SENTENCE_BUILDER_API_USERNAME: ${SENTENCE_BUILDER_API_USERNAME}
      SENTENCE_BUILDER_API_PASSWORD: ${SENTENCE_BUILDER_API_PASSWORD}
      SENTENCE_BUILDER_API_JWT_SECRET: ${SENTENCE_BUILDER_API_JWT_SECRET}
      SENTENCE_BUILDER_API_PRIVATE_PATH: ${SENTENCE_BUILDER_API_PRIVATE_PATH}
      SENTENCE_BUILDER_API_PUBLIC_PATH: ${SENTENCE_BUILDER_API_PUBLIC_PATH}
      SENTENCE_BUILDER_API_ORIGINS: ${SENTENCE_BUILDER_API_ORIGINS}
    depends_on:
      - mongo
      - postgres
    networks:
      - sentence-builder


# Data storage services
  mongo:
    container_name: sentence-builder-api-mongo-db
    ports:
      - '${MONGO_PORT}:27017'
    restart: always
    image: 'mongo:4.4.14-focal'
    environment:
      MONGO_INITDB_DATABASE: ${SENTENCE_BUILDER_API_MONGO_DB_NAME}
    volumes:
      - sb-api-mongo-data:/data/db
    networks:
      - sentence-builder

  postgres:
    container_name: sentence-builder-api-postgres-db
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_DB: ${SENTENCE_BUILDER_API_POSTGRES_DB}
      POSTGRES_USER: ${SENTENCE_BUILDER_API_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SENTENCE_BUILDER_API_POSTGRES_PASS}
    volumes:
      - sb-api-postgres-data:/var/lib/postgresql/data
    networks:
      - sentence-builder

volumes:
  sb-api-postgres-data:
    driver: local
  sb-api-mongo-data:

networks:
  sentence-builder:
    driver: bridge