spring:
  datasource:
    url: ${SENTENCE_BUILDER_API_POSTGRES_URL}
    username: ${SENTENCE_BUILDER_API_POSTGRES_USER}
    password: ${SENTENCE_BUILDER_API_POSTGRES_PASS}
  data:
    mongodb:
      uri: ${SENTENCE_BUILDER_MONGODB_URL}

admin:
  username: ${SENTENCE_BUILDER_API_USERNAME}
  password: ${SENTENCE_BUILDER_API_PASSWORD}

jwt:
  secret: ${SENTENCE_BUILDER_API_JWT_SECRET}
  lifetime: 24

api:
  private: /api/v2
  public: /api/v1

cors:
  origins: ${SENTENCE_BUILDER_API_ORIGINS}
  methods: GET, POST, DELETE, OPTIONS